source 'https://rubygems.org'
ruby '2.2.3'
gem 'rails', '4.2.4'
gem 'pg'
gem 'bourbon'
gem 'sass-rails', '~> 5.0'
gem 'materialize-sass'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'devise'
gem 'gibbon', '~> 1.2.0'
gem 'braintree'
gem 'sucker_punch'
group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
group :development do
  gem 'capistrano', '~> 3.4.0'
  gem 'capistrano-rails', '~> 1.1'
  gem 'capistrano-rvm'
  gem 'capistrano-bundler'
  gem 'capistrano-postgresql'
  gem 'capistrano-secrets-yml'
  gem 'capistrano-safe-deploy-to'
  gem 'capistrano-passenger'
  gem 'better_errors'
  gem 'quiet_assets'
  gem 'rails_layout'
end
group :production do
  gem 'rails_12factor'
  gem 'google-analytics-rails'
  gem 'passenger'
end